name: test and deploy

on:
  push:
  workflow_dispatch:
    inputs:
      actions:
        description: "Que souhaitez-vous faire ?"
        required: true
        type: choice
        options:
          - déploiement
          - test add
          - test all
        dfault: "déploiement"
